[package]
name = "oxygenlance"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror = "1.0.65"

[build-dependencies]
cc = "1.1.31"

[dev-dependencies]
anyhow = "1.0.91"
clap = { version = "4.5.20", features = ["derive"] }
